MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=0 python main.py \
  --env_name=antsoccer-arena-navigate-v0 \
  --agent=agents/empowerment.py \
  --agent.num_skills=5 \
  --agent.lr=3e-4 \
  --agent.batch_size=1024 \
  --agent.value_p_curgoal=0.0 \
  --agent.value_p_trajgoal=1.0 \
  --agent.value_p_randomgoal=0.0 \
  --agent.value_geom_sample=True \
  --train_steps=1000000 \
  --eval_interval=20000 \
  --agent.discount=0.9